(module
  (import "wasi_snapshot_preview1" "fd_read" (func $fd_read (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 512)
  (global $IN i32 (i32.const 1048576))
  (global $OUT i32 (i32.const 17825792))
  (global $o (mut i32) (i32.const 17825792))
  (global $i (mut i32) (i32.const 0))
  (global $n (mut i32) (i32.const 0))

  (func $read_all (result i32) (local $n i32)
    (loop $l
      (i32.store (i32.const 0) (i32.add (global.get $IN) (local.get $n)))
      (i32.store (i32.const 4) (i32.sub (i32.const 16777216) (local.get $n)))
      (i32.store (i32.const 8) (i32.const 0))
      (drop (call $fd_read (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 8)))
      (if (i32.gt_s (i32.load (i32.const 8)) (i32.const 0))
        (then (local.set $n (i32.add (local.get $n) (i32.load (i32.const 8)))) (br $l))))
    (local.get $n))
  (func $write_all (param $p i32) (param $len i32)
    (loop $l
      (if (i32.gt_s (local.get $len) (i32.const 0)) (then
        (i32.store (i32.const 16) (local.get $p))
        (i32.store (i32.const 20) (local.get $len))
        (i32.store (i32.const 24) (i32.const 0))
        (drop (call $fd_write (i32.const 1) (i32.const 16) (i32.const 1) (i32.const 24)))
        (if (i32.le_s (i32.load (i32.const 24)) (i32.const 0)) (then (return)))
        (local.set $p (i32.add (local.get $p) (i32.load (i32.const 24))))
        (local.set $len (i32.sub (local.get $len) (i32.load (i32.const 24))))
        (br $l)))))
  (func $put (param $b i32)
    (i32.store8 (global.get $o) (local.get $b))
    (global.set $o (i32.add (global.get $o) (i32.const 1))))
  (func $put_i64 (param $v i64) (local $u i64) (local $p i32)
    (local.set $p (i32.const 96))
    (local.set $u (if (result i64) (i64.lt_s (local.get $v) (i64.const 0))
      (then (i64.sub (i64.const 0) (local.get $v))) (else (local.get $v))))
    (loop $d
      (local.set $p (i32.sub (local.get $p) (i32.const 1)))
      (i32.store8 (local.get $p) (i32.wrap_i64 (i64.add (i64.rem_u (local.get $u) (i64.const 10)) (i64.const 48))))
      (local.set $u (i64.div_u (local.get $u) (i64.const 10)))
      (br_if $d (i64.ne (local.get $u) (i64.const 0))))
    (if (i64.lt_s (local.get $v) (i64.const 0)) (then (call $put (i32.const 45))))
    (loop $c
      (call $put (i32.load8_u (local.get $p)))
      (local.set $p (i32.add (local.get $p) (i32.const 1)))
      (br_if $c (i32.lt_u (local.get $p) (i32.const 96)))))
  ;; skip spaces; return current char or 0 at end
  (func $peek (result i32) (local $c i32)
    (loop $l
      (if (i32.ge_u (global.get $i) (global.get $n)) (then (return (i32.const 0))))
      (local.set $c (i32.load8_u (i32.add (global.get $IN) (global.get $i))))
      (if (i32.eq (local.get $c) (i32.const 32)) (then
        (global.set $i (i32.add (global.get $i) (i32.const 1))) (br $l))))
    (local.get $c))
  (func $adv (global.set $i (i32.add (global.get $i) (i32.const 1))))

  (func $expr (result i64) (local $v i64) (local $op i32)
    (local.set $v (call $term))
    (loop $l
      (local.set $op (call $peek))
      (if (i32.or (i32.eq (local.get $op) (i32.const 43)) (i32.eq (local.get $op) (i32.const 45))) (then
        (call $adv)
        (if (i32.eq (local.get $op) (i32.const 43))
          (then (local.set $v (i64.add (local.get $v) (call $term))))
          (else (local.set $v (i64.sub (local.get $v) (call $term)))))
        (br $l))))
    (local.get $v))
  (func $term (result i64) (local $v i64) (local $op i32)
    (local.set $v (call $unary))
    (loop $l
      (local.set $op (call $peek))
      (if (i32.or (i32.eq (local.get $op) (i32.const 42)) (i32.eq (local.get $op) (i32.const 47))) (then
        (call $adv)
        (if (i32.eq (local.get $op) (i32.const 42))
          (then (local.set $v (i64.mul (local.get $v) (call $unary))))
          (else (local.set $v (i64.div_s (local.get $v) (call $unary)))))
        (br $l))))
    (local.get $v))
  (func $unary (result i64) (local $c i32) (local $v i64) (local $d i32)
    (local.set $c (call $peek))
    (if (i32.eq (local.get $c) (i32.const 45)) (then
      (call $adv) (return (i64.sub (i64.const 0) (call $unary)))))
    (if (i32.eq (local.get $c) (i32.const 40)) (then
      (call $adv)
      (local.set $v (call $expr))
      (drop (call $peek))
      (call $adv)
      (return (local.get $v))))
    (block $e (loop $l
      (br_if $e (i32.ge_u (global.get $i) (global.get $n)))
      (local.set $d (i32.sub (i32.load8_u (i32.add (global.get $IN) (global.get $i))) (i32.const 48)))
      (br_if $e (i32.gt_u (local.get $d) (i32.const 9)))
      (local.set $v (i64.add (i64.mul (local.get $v) (i64.const 10)) (i64.extend_i32_u (local.get $d))))
      (call $adv)
      (br $l)))
    (local.get $v))

  (func (export "_start") (local $c i32)
    (global.set $n (call $read_all))
    (block $done (loop $line
      (br_if $done (i32.ge_u (global.get $i) (global.get $n)))
      (local.set $c (i32.load8_u (i32.add (global.get $IN) (global.get $i))))
      (if (i32.le_u (local.get $c) (i32.const 32)) (then (call $adv) (br $line)))
      (call $put_i64 (call $expr))
      (call $put (i32.const 10))
      (block $e (loop $s
        (br_if $e (i32.ge_u (global.get $i) (global.get $n)))
        (local.set $c (i32.load8_u (i32.add (global.get $IN) (global.get $i))))
        (call $adv)
        (br_if $s (i32.ne (local.get $c) (i32.const 10)))))
      (br $line)))
    (call $write_all (global.get $OUT) (i32.sub (global.get $o) (global.get $OUT))))
)
