(module
  (import "wasi_snapshot_preview1" "fd_read" (func $fd_read (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 64)
  (data (i32.const 128) "div0\n")
  (data (i32.const 144) "overflow\n")
  (global $IN i32 (i32.const 1048576))
  (global $OUT i32 (i32.const 2097152))
  (global $o (mut i32) (i32.const 2097152))
  (global $i (mut i32) (i32.const 0))
  (global $n (mut i32) (i32.const 0))

  (func $read_all (result i32) (local $n i32)
    (loop $l
      (i32.store (i32.const 0) (i32.add (global.get $IN) (local.get $n)))
      (i32.store (i32.const 4) (i32.sub (i32.const 1048576) (local.get $n)))
      (i32.store (i32.const 8) (i32.const 0))
      (drop (call $fd_read (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 8)))
      (if (i32.gt_s (i32.load (i32.const 8)) (i32.const 0))
        (then (local.set $n (i32.add (local.get $n) (i32.load (i32.const 8)))) (br $l))))
    (local.get $n))
  (func $write_all (param $p i32) (param $len i32)
    (loop $l
      (if (i32.gt_s (local.get $len) (i32.const 0)) (then
        (i32.store (i32.const 16) (local.get $p))
        (i32.store (i32.const 20) (local.get $len))
        (i32.store (i32.const 24) (i32.const 0))
        (drop (call $fd_write (i32.const 1) (i32.const 16) (i32.const 1) (i32.const 24)))
        (if (i32.le_s (i32.load (i32.const 24)) (i32.const 0)) (then (return)))
        (local.set $p (i32.add (local.get $p) (i32.load (i32.const 24))))
        (local.set $len (i32.sub (local.get $len) (i32.load (i32.const 24))))
        (br $l)))))
  (func $at (param $i i32) (result i32) (i32.load8_u (i32.add (global.get $IN) (local.get $i))))
  (func $put (param $b i32)
    (i32.store8 (global.get $o) (local.get $b))
    (global.set $o (i32.add (global.get $o) (i32.const 1))))
  (func $puts (param $p i32) (param $len i32)
    (memory.copy (global.get $o) (local.get $p) (local.get $len))
    (global.set $o (i32.add (global.get $o) (local.get $len))))
  (func $put_i64 (param $v i64) (local $u i64) (local $p i32)
    (local.set $p (i32.const 96))
    (local.set $u (if (result i64) (i64.lt_s (local.get $v) (i64.const 0))
      (then (i64.sub (i64.const 0) (local.get $v))) (else (local.get $v))))
    (loop $d
      (local.set $p (i32.sub (local.get $p) (i32.const 1)))
      (i32.store8 (local.get $p) (i32.wrap_i64 (i64.add (i64.rem_u (local.get $u) (i64.const 10)) (i64.const 48))))
      (local.set $u (i64.div_u (local.get $u) (i64.const 10)))
      (br_if $d (i64.ne (local.get $u) (i64.const 0))))
    (if (i64.lt_s (local.get $v) (i64.const 0)) (then (call $put (i32.const 45))))
    (loop $c
      (call $put (i32.load8_u (local.get $p)))
      (local.set $p (i32.add (local.get $p) (i32.const 1)))
      (br_if $c (i32.lt_u (local.get $p) (i32.const 96)))))
  (func $int (result i64) (local $v i64) (local $neg i32) (local $c i32)
    (block $e (loop $s
      (br_if $e (i32.ge_u (global.get $i) (global.get $n)))
      (br_if $e (i32.gt_u (call $at (global.get $i)) (i32.const 32)))
      (global.set $i (i32.add (global.get $i) (i32.const 1)))
      (br $s)))
    (if (i32.eq (call $at (global.get $i)) (i32.const 45)) (then
      (local.set $neg (i32.const 1)) (global.set $i (i32.add (global.get $i) (i32.const 1)))))
    (block $e (loop $d
      (br_if $e (i32.ge_u (global.get $i) (global.get $n)))
      (local.set $c (i32.sub (call $at (global.get $i)) (i32.const 48)))
      (br_if $e (i32.gt_u (local.get $c) (i32.const 9)))
      (local.set $v (i64.add (i64.mul (local.get $v) (i64.const 10)) (i64.extend_i32_u (local.get $c))))
      (global.set $i (i32.add (global.get $i) (i32.const 1)))
      (br $d)))
    (if (result i64) (local.get $neg) (then (i64.sub (i64.const 0) (local.get $v))) (else (local.get $v))))

  (func (export "_start") (local $a i64) (local $b i64) (local $q i64) (local $r i64)
    (global.set $n (call $read_all))
    (block $done (loop $line
      (block $e (loop $s
        (br_if $e (i32.ge_u (global.get $i) (global.get $n)))
        (br_if $e (i32.gt_u (call $at (global.get $i)) (i32.const 32)))
        (global.set $i (i32.add (global.get $i) (i32.const 1)))
        (br $s)))
      (br_if $done (i32.ge_u (global.get $i) (global.get $n)))
      (local.set $a (call $int))
      (local.set $b (call $int))
      (if (i64.eqz (local.get $b))
        (then (call $puts (i32.const 128) (i32.const 5)))
        (else (if (i32.and (i64.eq (local.get $a) (i64.const 0x8000000000000000)) (i64.eq (local.get $b) (i64.const -1)))
          (then (call $puts (i32.const 144) (i32.const 9)))
          (else
            (local.set $q (i64.div_s (local.get $a) (local.get $b)))
            (local.set $r (i64.rem_s (local.get $a) (local.get $b)))
            (if (i32.and (i64.ne (local.get $r) (i64.const 0))
                         (i64.lt_s (i64.xor (local.get $r) (local.get $b)) (i64.const 0)))
              (then
                (local.set $q (i64.sub (local.get $q) (i64.const 1)))
                (local.set $r (i64.add (local.get $r) (local.get $b)))))
            (call $put_i64 (local.get $q))
            (call $put (i32.const 32))
            (call $put_i64 (local.get $r))
            (call $put (i32.const 10))))))
      (br $line)))
    (call $write_all (global.get $OUT) (i32.sub (global.get $o) (global.get $OUT))))
)
