(module
  (import "wasi_snapshot_preview1" "fd_read" (func $fd_read (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 512)
  (global $IN i32 (i32.const 1048576))
  (global $OUT i32 (i32.const 17825792))
  (global $KEYS i32 (i32.const 4096))
  (global $VALS i32 (i32.const 8192))
  (global $STAMP i32 (i32.const 12288))
  (global $o (mut i32) (i32.const 17825792))
  (global $i (mut i32) (i32.const 0))
  (global $n (mut i32) (i32.const 0))

  (func $read_all (result i32) (local $n i32)
    (loop $l
      (i32.store (i32.const 0) (i32.add (global.get $IN) (local.get $n)))
      (i32.store (i32.const 4) (i32.sub (i32.const 16777216) (local.get $n)))
      (i32.store (i32.const 8) (i32.const 0))
      (drop (call $fd_read (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 8)))
      (if (i32.gt_s (i32.load (i32.const 8)) (i32.const 0))
        (then (local.set $n (i32.add (local.get $n) (i32.load (i32.const 8)))) (br $l))))
    (local.get $n))
  (func $write_all (param $p i32) (param $len i32)
    (loop $l
      (if (i32.gt_s (local.get $len) (i32.const 0)) (then
        (i32.store (i32.const 16) (local.get $p))
        (i32.store (i32.const 20) (local.get $len))
        (i32.store (i32.const 24) (i32.const 0))
        (drop (call $fd_write (i32.const 1) (i32.const 16) (i32.const 1) (i32.const 24)))
        (if (i32.le_s (i32.load (i32.const 24)) (i32.const 0)) (then (return)))
        (local.set $p (i32.add (local.get $p) (i32.load (i32.const 24))))
        (local.set $len (i32.sub (local.get $len) (i32.load (i32.const 24))))
        (br $l)))))
  (func $at (param $i i32) (result i32) (i32.load8_u (i32.add (global.get $IN) (local.get $i))))
  (func $put (param $b i32)
    (i32.store8 (global.get $o) (local.get $b))
    (global.set $o (i32.add (global.get $o) (i32.const 1))))
  (func $put_u32 (param $v i32) (local $p i32)
    (local.set $p (i32.const 96))
    (loop $d
      (local.set $p (i32.sub (local.get $p) (i32.const 1)))
      (i32.store8 (local.get $p) (i32.add (i32.rem_u (local.get $v) (i32.const 10)) (i32.const 48)))
      (local.set $v (i32.div_u (local.get $v) (i32.const 10)))
      (br_if $d (local.get $v)))
    (loop $c
      (call $put (i32.load8_u (local.get $p)))
      (local.set $p (i32.add (local.get $p) (i32.const 1)))
      (br_if $c (i32.lt_u (local.get $p) (i32.const 96)))))
  ;; skip non-digits then read an unsigned integer
  (func $uint (result i32) (local $v i32) (local $c i32)
    (block $e (loop $s
      (br_if $e (i32.ge_u (global.get $i) (global.get $n)))
      (br_if $e (i32.le_u (i32.sub (call $at (global.get $i)) (i32.const 48)) (i32.const 9)))
      (global.set $i (i32.add (global.get $i) (i32.const 1)))
      (br $s)))
    (block $e (loop $d
      (br_if $e (i32.ge_u (global.get $i) (global.get $n)))
      (local.set $c (i32.sub (call $at (global.get $i)) (i32.const 48)))
      (br_if $e (i32.gt_u (local.get $c) (i32.const 9)))
      (local.set $v (i32.add (i32.mul (local.get $v) (i32.const 10)) (local.get $c)))
      (global.set $i (i32.add (global.get $i) (i32.const 1)))
      (br $d)))
    (local.get $v))

  (func (export "_start")
    (local $cap i32) (local $cnt i32) (local $clock i32) (local $op i32) (local $k i32) (local $v i32)
    (local $j i32) (local $min i32) (local $s i32)
    (global.set $n (call $read_all))
    (local.set $cap (call $uint))
    (block $done (loop $ops
      (br_if $done (i32.ge_u (global.get $i) (global.get $n)))
      (local.set $op (call $at (global.get $i)))
      (if (i32.le_u (local.get $op) (i32.const 32)) (then
        (global.set $i (i32.add (global.get $i) (i32.const 1))) (br $ops)))
      (global.set $i (i32.add (global.get $i) (i32.const 3)))
      (local.set $k (call $uint))
      (local.set $j (i32.const 0))
      (block $f (loop $find
        (br_if $f (i32.ge_u (local.get $j) (local.get $cnt)))
        (br_if $f (i32.eq (i32.load (i32.add (global.get $KEYS) (i32.shl (local.get $j) (i32.const 2)))) (local.get $k)))
        (local.set $j (i32.add (local.get $j) (i32.const 1)))
        (br $find)))
      (local.set $clock (i32.add (local.get $clock) (i32.const 1)))
      (if (i32.eq (local.get $op) (i32.const 103))
        (then
          (if (i32.lt_u (local.get $j) (local.get $cnt))
            (then
              (i32.store (i32.add (global.get $STAMP) (i32.shl (local.get $j) (i32.const 2))) (local.get $clock))
              (call $put_u32 (i32.load (i32.add (global.get $VALS) (i32.shl (local.get $j) (i32.const 2))))))
            (else (call $put (i32.const 45)) (call $put (i32.const 49))))
          (call $put (i32.const 10)))
        (else
          (local.set $v (call $uint))
          (if (i32.ge_u (local.get $j) (local.get $cnt)) (then
            (if (i32.lt_u (local.get $cnt) (local.get $cap))
              (then (local.set $j (local.get $cnt)) (local.set $cnt (i32.add (local.get $cnt) (i32.const 1))))
              (else
                (local.set $j (i32.const 0))
                (local.set $min (i32.load (global.get $STAMP)))
                (local.set $s (i32.const 1))
                (block $e (loop $ev
                  (br_if $e (i32.ge_u (local.get $s) (local.get $cnt)))
                  (if (i32.lt_u (i32.load (i32.add (global.get $STAMP) (i32.shl (local.get $s) (i32.const 2)))) (local.get $min))
                    (then
                      (local.set $min (i32.load (i32.add (global.get $STAMP) (i32.shl (local.get $s) (i32.const 2)))))
                      (local.set $j (local.get $s))))
                  (local.set $s (i32.add (local.get $s) (i32.const 1)))
                  (br $ev)))))
            (i32.store (i32.add (global.get $KEYS) (i32.shl (local.get $j) (i32.const 2))) (local.get $k))))
          (i32.store (i32.add (global.get $VALS) (i32.shl (local.get $j) (i32.const 2))) (local.get $v))
          (i32.store (i32.add (global.get $STAMP) (i32.shl (local.get $j) (i32.const 2))) (local.get $clock))))
      (br $ops)))
    (call $write_all (global.get $OUT) (i32.sub (global.get $o) (global.get $OUT))))
)
