(module
  (import "wasi_snapshot_preview1" "fd_read" (func $fd_read (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 512)
  (global $IN i32 (i32.const 1048576))
  (global $OUT i32 (i32.const 17825792))
  (global $A i32 (i32.const 25165824))
  (global $B i32 (i32.const 27262976))
  (global $CNT i32 (i32.const 29360128))
  (global $o (mut i32) (i32.const 17825792))

  (func $read_all (result i32) (local $n i32)
    (loop $l
      (i32.store (i32.const 0) (i32.add (global.get $IN) (local.get $n)))
      (i32.store (i32.const 4) (i32.sub (i32.const 16777216) (local.get $n)))
      (i32.store (i32.const 8) (i32.const 0))
      (drop (call $fd_read (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 8)))
      (if (i32.gt_s (i32.load (i32.const 8)) (i32.const 0))
        (then (local.set $n (i32.add (local.get $n) (i32.load (i32.const 8)))) (br $l))))
    (local.get $n))
  (func $write_all (param $p i32) (param $len i32)
    (loop $l
      (if (i32.gt_s (local.get $len) (i32.const 0)) (then
        (i32.store (i32.const 16) (local.get $p))
        (i32.store (i32.const 20) (local.get $len))
        (i32.store (i32.const 24) (i32.const 0))
        (drop (call $fd_write (i32.const 1) (i32.const 16) (i32.const 1) (i32.const 24)))
        (if (i32.le_s (i32.load (i32.const 24)) (i32.const 0)) (then (return)))
        (local.set $p (i32.add (local.get $p) (i32.load (i32.const 24))))
        (local.set $len (i32.sub (local.get $len) (i32.load (i32.const 24))))
        (br $l)))))
  (func $at (param $i i32) (result i32) (i32.load8_u (i32.add (global.get $IN) (local.get $i))))
  (func $put (param $b i32)
    (i32.store8 (global.get $o) (local.get $b))
    (global.set $o (i32.add (global.get $o) (i32.const 1))))
  (func $put_i64 (param $v i64) (local $u i64) (local $p i32)
    (local.set $p (i32.const 96))
    (local.set $u (if (result i64) (i64.lt_s (local.get $v) (i64.const 0))
      (then (i64.sub (i64.const 0) (local.get $v))) (else (local.get $v))))
    (loop $d
      (local.set $p (i32.sub (local.get $p) (i32.const 1)))
      (i32.store8 (local.get $p) (i32.wrap_i64 (i64.add (i64.rem_u (local.get $u) (i64.const 10)) (i64.const 48))))
      (local.set $u (i64.div_u (local.get $u) (i64.const 10)))
      (br_if $d (i64.ne (local.get $u) (i64.const 0))))
    (if (i64.lt_s (local.get $v) (i64.const 0)) (then (call $put (i32.const 45))))
    (loop $c
      (call $put (i32.load8_u (local.get $p)))
      (local.set $p (i32.add (local.get $p) (i32.const 1)))
      (br_if $c (i32.lt_u (local.get $p) (i32.const 96)))))

  (func (export "_start")
    (local $n i32) (local $i i32) (local $c i32) (local $cnt i32) (local $v i64) (local $neg i32)
    (local $src i32) (local $dst i32) (local $sh i64) (local $j i32) (local $x i64) (local $bk i32) (local $sum i32) (local $t i32)
    (local.set $n (call $read_all))
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $c (call $at (local.get $i)))
      (if (i32.le_u (local.get $c) (i32.const 32)) (then
        (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $next)))
      (local.set $neg (i32.const 0))
      (if (i32.eq (local.get $c) (i32.const 45)) (then
        (local.set $neg (i32.const 1)) (local.set $i (i32.add (local.get $i) (i32.const 1)))))
      (local.set $v (i64.const 0))
      (block $e (loop $d
        (br_if $e (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $c (i32.sub (call $at (local.get $i)) (i32.const 48)))
        (br_if $e (i32.gt_u (local.get $c) (i32.const 9)))
        (local.set $v (i64.add (i64.mul (local.get $v) (i64.const 10)) (i64.extend_i32_u (local.get $c))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $d)))
      (if (local.get $neg) (then (local.set $v (i64.sub (i64.const 0) (local.get $v)))))
      (i64.store (i32.add (global.get $A) (i32.shl (local.get $cnt) (i32.const 3)))
                 (i64.xor (local.get $v) (i64.const 0x8000000000000000)))
      (local.set $cnt (i32.add (local.get $cnt) (i32.const 1)))
      (br $next)))
    (local.set $src (global.get $A))
    (local.set $dst (global.get $B))
    (block $pd (loop $pass
      (br_if $pd (i64.ge_u (local.get $sh) (i64.const 64)))
      (memory.fill (global.get $CNT) (i32.const 0) (i32.const 1024))
      (local.set $j (i32.const 0))
      (block $e (loop $h
        (br_if $e (i32.ge_u (local.get $j) (local.get $cnt)))
        (local.set $bk (i32.add (global.get $CNT) (i32.shl (i32.wrap_i64 (i64.and
            (i64.shr_u (i64.load (i32.add (local.get $src) (i32.shl (local.get $j) (i32.const 3)))) (local.get $sh))
            (i64.const 255))) (i32.const 2))))
        (i32.store (local.get $bk) (i32.add (i32.load (local.get $bk)) (i32.const 1)))
        (local.set $j (i32.add (local.get $j) (i32.const 1)))
        (br $h)))
      (local.set $sum (i32.const 0))
      (local.set $j (i32.const 0))
      (loop $p
        (local.set $bk (i32.add (global.get $CNT) (i32.shl (local.get $j) (i32.const 2))))
        (local.set $t (i32.load (local.get $bk)))
        (i32.store (local.get $bk) (local.get $sum))
        (local.set $sum (i32.add (local.get $sum) (local.get $t)))
        (local.set $j (i32.add (local.get $j) (i32.const 1)))
        (br_if $p (i32.lt_u (local.get $j) (i32.const 256))))
      (local.set $j (i32.const 0))
      (block $e (loop $s
        (br_if $e (i32.ge_u (local.get $j) (local.get $cnt)))
        (local.set $x (i64.load (i32.add (local.get $src) (i32.shl (local.get $j) (i32.const 3)))))
        (local.set $bk (i32.add (global.get $CNT) (i32.shl (i32.wrap_i64 (i64.and
            (i64.shr_u (local.get $x) (local.get $sh)) (i64.const 255))) (i32.const 2))))
        (local.set $t (i32.load (local.get $bk)))
        (i64.store (i32.add (local.get $dst) (i32.shl (local.get $t) (i32.const 3))) (local.get $x))
        (i32.store (local.get $bk) (i32.add (local.get $t) (i32.const 1)))
        (local.set $j (i32.add (local.get $j) (i32.const 1)))
        (br $s)))
      (local.set $t (local.get $src))
      (local.set $src (local.get $dst))
      (local.set $dst (local.get $t))
      (local.set $sh (i64.add (local.get $sh) (i64.const 8)))
      (br $pass)))
    (local.set $j (i32.const 0))
    (block $e (loop $w
      (br_if $e (i32.ge_u (local.get $j) (local.get $cnt)))
      (call $put_i64 (i64.xor (i64.load (i32.add (local.get $src) (i32.shl (local.get $j) (i32.const 3))))
                              (i64.const 0x8000000000000000)))
      (call $put (i32.const 10))
      (local.set $j (i32.add (local.get $j) (i32.const 1)))
      (br $w)))
    (call $write_all (global.get $OUT) (i32.sub (global.get $o) (global.get $OUT))))
)
