(module
  (import "wasi_snapshot_preview1" "fd_read" (func $fd_read (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 512)
  (data (i32.const 128) "valid\n")
  (data (i32.const 144) "invalid\n")
  (global $IN i32 (i32.const 1048576))

  (func $read_all (result i32) (local $n i32)
    (loop $l
      (i32.store (i32.const 0) (i32.add (global.get $IN) (local.get $n)))
      (i32.store (i32.const 4) (i32.sub (i32.const 16777216) (local.get $n)))
      (i32.store (i32.const 8) (i32.const 0))
      (drop (call $fd_read (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 8)))
      (if (i32.gt_s (i32.load (i32.const 8)) (i32.const 0))
        (then (local.set $n (i32.add (local.get $n) (i32.load (i32.const 8)))) (br $l))))
    (local.get $n))
  (func $b (param $i i32) (result i32) (i32.load8_u (i32.add (global.get $IN) (local.get $i))))
  (func $say (param $p i32) (param $len i32)
    (i32.store (i32.const 16) (local.get $p))
    (i32.store (i32.const 20) (local.get $len))
    (drop (call $fd_write (i32.const 1) (i32.const 16) (i32.const 1) (i32.const 24))))

  ;; returns 1 if valid
  (func $check (param $n i32) (result i32)
    (local $i i32) (local $c i32) (local $k i32) (local $lo i32) (local $hi i32) (local $x i32)
    (loop $l
      (if (i32.ge_u (local.get $i) (local.get $n)) (then (return (i32.const 1))))
      (local.set $c (call $b (local.get $i)))
      (if (i32.lt_u (local.get $c) (i32.const 0x80)) (then
        (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $l)))
      (if (i32.lt_u (local.get $c) (i32.const 0xC2)) (then (return (i32.const 0))))
      (local.set $lo (i32.const 0x80))
      (local.set $hi (i32.const 0xBF))
      (if (i32.lt_u (local.get $c) (i32.const 0xE0))
        (then (local.set $k (i32.const 1)))
        (else (if (i32.lt_u (local.get $c) (i32.const 0xF0))
          (then
            (local.set $k (i32.const 2))
            (if (i32.eq (local.get $c) (i32.const 0xE0)) (then (local.set $lo (i32.const 0xA0))))
            (if (i32.eq (local.get $c) (i32.const 0xED)) (then (local.set $hi (i32.const 0x9F)))))
          (else (if (i32.lt_u (local.get $c) (i32.const 0xF5))
            (then
              (local.set $k (i32.const 3))
              (if (i32.eq (local.get $c) (i32.const 0xF0)) (then (local.set $lo (i32.const 0x90))))
              (if (i32.eq (local.get $c) (i32.const 0xF4)) (then (local.set $hi (i32.const 0x8F)))))
            (else (return (i32.const 0))))))))
      (if (i32.ge_u (i32.add (local.get $i) (local.get $k)) (local.get $n)) (then (return (i32.const 0))))
      (local.set $x (call $b (i32.add (local.get $i) (i32.const 1))))
      (if (i32.or (i32.lt_u (local.get $x) (local.get $lo)) (i32.gt_u (local.get $x) (local.get $hi)))
        (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 2)))
      (local.set $k (i32.sub (local.get $k) (i32.const 1)))
      (block $d (loop $cl
        (br_if $d (i32.eqz (local.get $k)))
        (if (i32.ne (i32.and (call $b (local.get $i)) (i32.const 0xC0)) (i32.const 0x80))
          (then (return (i32.const 0))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $k (i32.sub (local.get $k) (i32.const 1)))
        (br $cl)))
      (br $l))
    (i32.const 1))

  (func (export "_start")
    (if (call $check (call $read_all))
      (then (call $say (i32.const 128) (i32.const 6)))
      (else (call $say (i32.const 144) (i32.const 8)))))
)
