(module
  (import "wasi_snapshot_preview1" "fd_read" (func $fd_read (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 900)
  (global $IN i32 (i32.const 1048576))
  (global $OUT i32 (i32.const 17825792))
  (global $TAB i32 (i32.const 34603008))   ;; 2^20 slots x 16: off, len, count(i64)
  (global $DIST i32 (i32.const 51380224))  ;; 2^20 x 4
  (global $o (mut i32) (i32.const 17825792))

  (func $read_all (result i32) (local $n i32)
    (loop $l
      (i32.store (i32.const 0) (i32.add (global.get $IN) (local.get $n)))
      (i32.store (i32.const 4) (i32.sub (i32.const 16777216) (local.get $n)))
      (i32.store (i32.const 8) (i32.const 0))
      (drop (call $fd_read (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 8)))
      (if (i32.gt_s (i32.load (i32.const 8)) (i32.const 0))
        (then (local.set $n (i32.add (local.get $n) (i32.load (i32.const 8)))) (br $l))))
    (local.get $n))
  (func $write_all (param $p i32) (param $len i32)
    (loop $l
      (if (i32.gt_s (local.get $len) (i32.const 0)) (then
        (i32.store (i32.const 16) (local.get $p))
        (i32.store (i32.const 20) (local.get $len))
        (i32.store (i32.const 24) (i32.const 0))
        (drop (call $fd_write (i32.const 1) (i32.const 16) (i32.const 1) (i32.const 24)))
        (if (i32.le_s (i32.load (i32.const 24)) (i32.const 0)) (then (return)))
        (local.set $p (i32.add (local.get $p) (i32.load (i32.const 24))))
        (local.set $len (i32.sub (local.get $len) (i32.load (i32.const 24))))
        (br $l)))))
  (func $at (param $i i32) (result i32) (i32.load8_u (i32.add (global.get $IN) (local.get $i))))
  (func $put (param $b i32)
    (i32.store8 (global.get $o) (local.get $b))
    (global.set $o (i32.add (global.get $o) (i32.const 1))))
  (func $put_u64 (param $u i64) (local $p i32)
    (local.set $p (i32.const 96))
    (loop $d
      (local.set $p (i32.sub (local.get $p) (i32.const 1)))
      (i32.store8 (local.get $p) (i32.wrap_i64 (i64.add (i64.rem_u (local.get $u) (i64.const 10)) (i64.const 48))))
      (local.set $u (i64.div_u (local.get $u) (i64.const 10)))
      (br_if $d (i64.ne (local.get $u) (i64.const 0))))
    (loop $c
      (call $put (i32.load8_u (local.get $p)))
      (local.set $p (i32.add (local.get $p) (i32.const 1)))
      (br_if $c (i32.lt_u (local.get $p) (i32.const 96)))))
  (func $slot (param $s i32) (result i32) (i32.add (global.get $TAB) (i32.shl (local.get $s) (i32.const 4))))
  (func $lower (param $c i32) (result i32)   ;; lowercase letter or -1
    (local.set $c (i32.or (local.get $c) (i32.const 32)))
    (if (result i32) (i32.le_u (i32.sub (local.get $c) (i32.const 97)) (i32.const 25))
      (then (local.get $c)) (else (i32.const -1))))
  ;; 1 if slot a ranks before slot b
  (func $better (param $a i32) (param $b i32) (result i32)
    (local $pa i32) (local $pb i32) (local $ca i64) (local $cb i64) (local $la i32) (local $lb i32) (local $i i32) (local $x i32) (local $y i32)
    (local.set $pa (call $slot (local.get $a)))
    (local.set $pb (call $slot (local.get $b)))
    (local.set $ca (i64.load offset=8 (local.get $pa)))
    (local.set $cb (i64.load offset=8 (local.get $pb)))
    (if (i64.gt_u (local.get $ca) (local.get $cb)) (then (return (i32.const 1))))
    (if (i64.lt_u (local.get $ca) (local.get $cb)) (then (return (i32.const 0))))
    (local.set $la (i32.load offset=4 (local.get $pa)))
    (local.set $lb (i32.load offset=4 (local.get $pb)))
    (loop $l
      (if (i32.ge_u (local.get $i) (local.get $la)) (then (return (i32.lt_u (local.get $la) (local.get $lb)))))
      (if (i32.ge_u (local.get $i) (local.get $lb)) (then (return (i32.const 0))))
      (local.set $x (call $at (i32.add (i32.load (local.get $pa)) (local.get $i))))
      (local.set $y (call $at (i32.add (i32.load (local.get $pb)) (local.get $i))))
      (if (i32.lt_u (local.get $x) (local.get $y)) (then (return (i32.const 1))))
      (if (i32.gt_u (local.get $x) (local.get $y)) (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $l))
    (i32.const 0))

  (func (export "_start")
    (local $n i32) (local $i i32) (local $c i32) (local $ws i32) (local $len i32) (local $h i64) (local $s i32)
    (local $p i32) (local $j i32) (local $eq i32) (local $nd i32) (local $k i32) (local $best i32) (local $lim i32) (local $t i32)
    (local.set $n (call $read_all))
    (block $scanned (loop $scan
      (br_if $scanned (i32.ge_u (local.get $i) (local.get $n)))
      (if (i32.lt_s (call $lower (call $at (local.get $i))) (i32.const 0)) (then
        (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $scan)))
      (local.set $ws (local.get $i))
      (local.set $h (i64.const 0xcbf29ce484222325))
      (block $e (loop $w
        (br_if $e (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $c (call $lower (call $at (local.get $i))))
        (br_if $e (i32.lt_s (local.get $c) (i32.const 0)))
        (i32.store8 (i32.add (global.get $IN) (local.get $i)) (local.get $c))
        (local.set $h (i64.mul (i64.xor (local.get $h) (i64.extend_i32_u (local.get $c))) (i64.const 0x100000001b3)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $w)))
      (local.set $len (i32.sub (local.get $i) (local.get $ws)))
      (local.set $s (i32.and (i32.wrap_i64 (local.get $h)) (i32.const 0xFFFFF)))
      (block $placed (loop $probe
        (local.set $p (call $slot (local.get $s)))
        (if (i32.eqz (i32.load offset=4 (local.get $p))) (then
          (i32.store (local.get $p) (local.get $ws))
          (i32.store offset=4 (local.get $p) (local.get $len))
          (i64.store offset=8 (local.get $p) (i64.const 1))
          (i32.store (i32.add (global.get $DIST) (i32.shl (local.get $nd) (i32.const 2))) (local.get $s))
          (local.set $nd (i32.add (local.get $nd) (i32.const 1)))
          (br $placed)))
        (if (i32.eq (i32.load offset=4 (local.get $p)) (local.get $len)) (then
          (local.set $eq (i32.const 1))
          (local.set $j (i32.const 0))
          (block $d (loop $cmp
            (br_if $d (i32.ge_u (local.get $j) (local.get $len)))
            (if (i32.ne (call $at (i32.add (i32.load (local.get $p)) (local.get $j)))
                        (call $at (i32.add (local.get $ws) (local.get $j))))
              (then (local.set $eq (i32.const 0)) (br $d)))
            (local.set $j (i32.add (local.get $j) (i32.const 1)))
            (br $cmp)))
          (if (local.get $eq) (then
            (i64.store offset=8 (local.get $p) (i64.add (i64.load offset=8 (local.get $p)) (i64.const 1)))
            (br $placed)))))
        (local.set $s (i32.and (i32.add (local.get $s) (i32.const 1)) (i32.const 0xFFFFF)))
        (br $probe)))
      (br $scan)))
    (local.set $lim (select (local.get $nd) (i32.const 10) (i32.lt_u (local.get $nd) (i32.const 10))))
    (block $done (loop $sel
      (br_if $done (i32.ge_u (local.get $k) (local.get $lim)))
      (local.set $best (local.get $k))
      (local.set $j (i32.add (local.get $k) (i32.const 1)))
      (block $e (loop $l
        (br_if $e (i32.ge_u (local.get $j) (local.get $nd)))
        (if (call $better (i32.load (i32.add (global.get $DIST) (i32.shl (local.get $j) (i32.const 2))))
                          (i32.load (i32.add (global.get $DIST) (i32.shl (local.get $best) (i32.const 2)))))
          (then (local.set $best (local.get $j))))
        (local.set $j (i32.add (local.get $j) (i32.const 1)))
        (br $l)))
      (local.set $t (i32.load (i32.add (global.get $DIST) (i32.shl (local.get $best) (i32.const 2)))))
      (i32.store (i32.add (global.get $DIST) (i32.shl (local.get $best) (i32.const 2)))
                 (i32.load (i32.add (global.get $DIST) (i32.shl (local.get $k) (i32.const 2)))))
      (i32.store (i32.add (global.get $DIST) (i32.shl (local.get $k) (i32.const 2))) (local.get $t))
      (local.set $p (call $slot (local.get $t)))
      (call $put_u64 (i64.load offset=8 (local.get $p)))
      (call $put (i32.const 32))
      (memory.copy (global.get $o) (i32.add (global.get $IN) (i32.load (local.get $p))) (i32.load offset=4 (local.get $p)))
      (global.set $o (i32.add (global.get $o) (i32.load offset=4 (local.get $p))))
      (call $put (i32.const 10))
      (local.set $k (i32.add (local.get $k) (i32.const 1)))
      (br $sel)))
    (call $write_all (global.get $OUT) (i32.sub (global.get $o) (global.get $OUT))))
)
